project_id = "vejqfpznzcohtbggkfhr"

[functions.energy-diagnosis]
verify_jwt = false

[functions.scheduled-jobs]
verify_jwt = false

[functions.admin-roles]
verify_jwt = false

[functions.devices]
verify_jwt = false

[functions.latest]
verify_jwt = false

[functions.timeseries]
verify_jwt = false
